<?php

// DO NOT EDIT THIS FILE
// Aliases are controlled from 'aliases' section of config.yml

global $project_config;

if (isset($project_config['aliases'])) {
  foreach ($project_config['aliases'] as $key => $config) {
    $aliases[$key] = $config;
  }
}
